# RDS PostgreSQL, private, with an RDS-managed master password.
#
# The password is the interesting decision here. manage_master_user_password makes RDS
# generate the value and own the Secrets Manager secret holding it, so Terraform never sees
# it and it never enters terraform.tfstate. The common alternative, a random_password resource
# plus an aws_secretsmanager_secret_version, writes the password into state in plaintext, and
# state is a file that gets copied around.
#
# Several settings here are demo-correct and production-wrong. Each one says so.

resource "aws_db_subnet_group" "main" {
  name       = "${var.project_name}-db-subnet-group"
  subnet_ids = var.private_subnet_ids

  # RDS requires subnets in at least two availability zones even for a single-AZ instance,
  # because it has to have somewhere to fail over to if you ever enable multi-AZ.
  description = "Private subnets. The instance has no route to or from the internet."

  tags = {
    Name = "${var.project_name}-db-subnet-group"
  }
}

resource "aws_db_instance" "main" {
  identifier = "${var.project_name}-db"

  engine = "postgres"
  # Major version only. RDS selects the current minor release, and pinning a full version
  # means the config breaks the day AWS retires that minor.
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  storage_type      = "gp3"
  # Encryption at rest with the default RDS key costs nothing. There is no reason to leave it
  # off, and it cannot be enabled later without a snapshot-and-restore.
  storage_encrypted = true

  db_name  = var.db_name
  username = var.db_username

  # RDS creates the password, stores it in Secrets Manager, and owns rotation. Terraform never
  # receives the value, so it cannot leak into state, tfvars, or a variable.
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [var.rds_sg_id]
  # No public IP and no route to the internet gateway. The security group is the second layer;
  # this is the first.
  publicly_accessible = false

  port = var.db_port

  # ---- demo-correct, production-wrong ----

  # Production: true, so a fat-fingered destroy is refused. Here it would make teardown fail,
  # and teardown is the cost guardrail.
  deletion_protection = false
  # Production: false, so destroying always leaves a recoverable snapshot. Here the data is
  # generated by a load test and a snapshot is a bill.
  skip_final_snapshot = true
  # Production: 7 days or more. Here backups protect nothing that matters and bill for storage.
  backup_retention_period = 0
  # Production: false, with upgrades applied in a maintenance window you chose. Here it keeps
  # the instance patched without any attention.
  auto_minor_version_upgrade = true
  # Production: false, so changes land in the maintenance window rather than mid-afternoon.
  apply_immediately = true

  # Deliberately absent: multi_az (doubles the bill), performance_insights_enabled, and
  # enhanced monitoring. All three are the right call on a real database and all three buy
  # nothing on an instance that lives for the length of one demo.

  tags = {
    Name = "${var.project_name}-db"
  }
}
